-- This module is the root of the CoarseBaumConnesConjectureCanonicalLaneLean Lean proof package.
import CoarseBaumConnesConjectureCanonicalLaneLean.Basic
import CoarseBaumConnesConjectureCanonicalLaneLean.SourcePackage
import CoarseBaumConnesConjectureCanonicalLaneLean.SourceDependencies
import CoarseBaumConnesConjectureCanonicalLaneLean.Formalization
import CoarseBaumConnesConjectureCanonicalLaneLean.ReviewerBridge
import CoarseBaumConnesConjectureCanonicalLaneLean.TheoremStatement
import CoarseBaumConnesConjectureCanonicalLaneLean.MathlibObjects
import CoarseBaumConnesConjectureCanonicalLaneLean.AdmissibleClass
import CoarseBaumConnesConjectureCanonicalLaneLean.Projection
import CoarseBaumConnesConjectureCanonicalLaneLean.BridgeLemmas
import CoarseBaumConnesConjectureCanonicalLaneLean.GateLemmas
import CoarseBaumConnesConjectureCanonicalLaneLean.FinalTheorem
import CoarseBaumConnesConjectureCanonicalLaneLean.MathlibStatement
